version: "3"

services:
  scylla-node1:
    build: ./.docker/scylla
    container_name: scylla-node1
    command: --smp 1
    environment:
      - "SCYLLA_JMX_ADDR=-ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=-r"
    expose:
      - "7199"
    ports:
      - 9042:9042
    volumes:
      - ./.docker/scylla/node1:/var/lib/scylla
      - ./.docker/scylla/scripts:/scripts

  scylla-node2:
    build: ./.docker/scylla
    container_name: scylla-node2
    command: --smp 1 --seeds=scylla-node1
    environment:
      - "SCYLLA_JMX_ADDR=-ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=-r"
    expose:
      - "7199"
    ports:
      - 9043:9042
    volumes:
      - ./.docker/scylla/node2:/var/lib/scylla

  scylla-node3:
    build: ./.docker/scylla
    container_name: scylla-node3
    command: --smp 1 --seeds=scylla-node1
    environment:
      - "SCYLLA_JMX_ADDR=-ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=-r"
    ports:
      - 9044:9042
    expose:
      - "7199"
    volumes:
      - ./.docker/scylla/node3:/var/lib/scylla
  
  app:
    build: .
    container_name: app
    ports:
      - '3003:3003'
    volumes:
      - ./src:/home/node/app/src
    environment:
      - DATACENTER=datacenter1
      - SCYLLA_CONTACT_POINTS=scylla-node1,scylla-node2,scylla-node3
      - SCYLLA_KEYSPACE=development
      - SCYLLA_PASSWORD=cassandra
      - SCYLLA_USERNAME=cassandra
      - PORT=3003
      - HOST=0.0.0.0
      - NODE_ENV=development
    depends_on:
      - scylla-node1
      - scylla-node2
      - scylla-node3
